server:
  port: 8081
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: 127.0.0.1
    port: 6379
